import {
  Sequelize,
  Deferrable,
  DataTypes as DT,
  Model,
  ModelCtor,
} from 'sequelize';

export default function applicationModel(
  sequelize: Sequelize,
  User: ModelCtor<Model>
) {
  return sequelize.define('Application', {
    userId: {
      type: DT.INTEGER,
      references: {
        model: User,
        key: 'id', // use autogenerated id column as FK
        deferrable:
          Deferrable.INITIALLY_DEFERRED as unknown as Deferrable.Deferrable,
        // it seems the type definitions in Sequelize don't match the desired usage,
        // ideally we'd remove the cast
      },
    },
    company: { type: DT.STRING },
    started: { type: DT.DATE, defaultValue: DT.NOW },
    updated: { type: DT.DATE, defaultValue: DT.NOW },
    notes: { type: DT.TEXT },
    uuid: { type: DT.UUID, defaultValue: DT.UUIDV4 },
  });
}
